// Code generated for kirillmc
// © kirillmc 2025
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kirillmc/starShipsCompany/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *Repository) Get(ctx context.Context, uuid model.PartUUID) (*model.Part, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartUUID) (*model.Part, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartUUID) *model.Part); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartUUID) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid model.PartUUID
func (_e *Repository_Expecter) Get(ctx interface{}, uuid interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *Repository_Get_Call) Run(run func(ctx context.Context, uuid model.PartUUID)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartUUID))
	})
	return _c
}

func (_c *Repository_Get_Call) Return(_a0 *model.Part, _a1 error) *Repository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(context.Context, model.PartUUID) (*model.Part, error)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *Repository) List(ctx context.Context) map[model.PartUUID]*model.Part {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 map[model.PartUUID]*model.Part
	if rf, ok := ret.Get(0).(func(context.Context) map[model.PartUUID]*model.Part); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.PartUUID]*model.Part)
		}
	}

	return r0
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) List(ctx interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_List_Call) Return(_a0 map[model.PartUUID]*model.Part) *Repository_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context.Context) map[model.PartUUID]*model.Part) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
