with-expecter: true
boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/kirillmc/starShipsCompany/order/internal/service:
    config:
      include-regex: ".*Service"
  github.com/kirillmc/starShipsCompany/order/internal/repository/pg:
    config:
      include-regex: ".*Repository"
  github.com/kirillmc/starShipsCompany/order/internal/client/grpc:
    config:
      include-regex: ".*Client"

  github.com/kirillmc/starShipsCompany/inventory/internal/service:
    config:
      include-regex: ".*Service"
  github.com/kirillmc/starShipsCompany/inventory/internal/repository/mongo:
    config:
      include-regex: ".*Repository"

  github.com/kirillmc/starShipsCompany/payment/internal/service:
    config:
      include-regex: ".*Service"