openapi: 3.0.3
info:
  title: OrderService API
  version: 1.0.0
  description: API для работы с данными о заказе

x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: order_v1
  clean: true

tags:
  - name: Order
    description: Сервис заказов управляет заказами на постройку космических кораблей.

servers:
  - url: "localhost"

paths:
  /api/v1/orders:
    $ref: ./paths/orders.yaml
  /api/v1/orders/{order_uuid}:
    $ref: ./paths/order_by_uuid.yaml
  /api/v1/orders/{order_uuid}/cancel:
    $ref: ./paths/order_cancel.yaml
  /api/v1/orders/{order_uuid}/pay:
    $ref: ./paths/order_pay.yaml