// Code generated for kirillmc
// © kirillmc 2025
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/kirillmc/starShipsCompany/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, order
func (_m *Repository) Create(ctx context.Context, order model.CreateOrder) (model.OrderInfo, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.OrderInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrder) (model.OrderInfo, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrder) model.OrderInfo); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(model.OrderInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateOrder) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.CreateOrder
func (_e *Repository_Expecter) Create(ctx interface{}, order interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, order model.CreateOrder)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateOrder))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 model.OrderInfo, _a1 error) *Repository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, model.CreateOrder) (model.OrderInfo, error)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, orderUUID
func (_m *Repository) Get(ctx context.Context, orderUUID model.OrderUUID) (model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderUUID) (model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderUUID) model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OrderUUID) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID model.OrderUUID
func (_e *Repository_Expecter) Get(ctx interface{}, orderUUID interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", ctx, orderUUID)}
}

func (_c *Repository_Get_Call) Run(run func(ctx context.Context, orderUUID model.OrderUUID)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderUUID))
	})
	return _c
}

func (_c *Repository_Get_Call) Return(_a0 model.Order, _a1 error) *Repository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(context.Context, model.OrderUUID) (model.Order, error)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, updateOrderParams
func (_m *Repository) UpdateOrder(ctx context.Context, updateOrderParams model.UpdateOrderParams) error {
	ret := _m.Called(ctx, updateOrderParams)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UpdateOrderParams) error); ok {
		r0 = rf(ctx, updateOrderParams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type Repository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - updateOrderParams model.UpdateOrderParams
func (_e *Repository_Expecter) UpdateOrder(ctx interface{}, updateOrderParams interface{}) *Repository_UpdateOrder_Call {
	return &Repository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, updateOrderParams)}
}

func (_c *Repository_UpdateOrder_Call) Run(run func(ctx context.Context, updateOrderParams model.UpdateOrderParams)) *Repository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UpdateOrderParams))
	})
	return _c
}

func (_c *Repository_UpdateOrder_Call) Return(_a0 error) *Repository_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateOrder_Call) RunAndReturn(run func(context.Context, model.UpdateOrderParams) error) *Repository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
