// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"net/http"
)

type codeRecorder struct {
	http.ResponseWriter
	status int
}

func (c *codeRecorder) WriteHeader(status int) {
	c.status = status
	c.ResponseWriter.WriteHeader(status)
}
